server:
  port: 0

spring:
  application:
    name: user-service
  cloud:
    config:
      name: ecommerce-dev, user-service-dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI}

logging:
  level:
    com.example.userservice.client: DEBUG