server:
  port: 0

spring:
  application:
    name: order-service
  cloud:
    config:
      name: ecommerce-dev, order-service-dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI}