server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    config:
      name: ecommerce-dev, api-gateway-service-dev
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URI}