server:
  port: 8888

spring:
  application:
    name: config-service
  config:
    import:
      - optional:file:./config-service/.env[.properties]
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}
  rabbitmq:
    host: ${RABBITMQ_ENDPOINT}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh