server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}
  rabbitmq:
    host: ${RABBITMQ_ENDPOINT}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

encrypt:
  key: ${ENCRYPT_KEY}
