server:
  port: 8888

spring:
  application:
    name: config-service
  config:
    import:
      - optional:file:./config-service/.env[.properties]
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI}